apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: {{ .Values.argocd.project }}
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.8.0
    helm:
      version: v3
      values: |
        global:
          leaderElection:
            namespace: cert-manager

        extraArgs:
          - --issuer-ambient-credentials

        securityContext:
          enabled: true
          fsGroup: 1001
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
