apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: {{ .Values.argocd.project }}
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.6.1
    helm:
      version: v3
      values: |
        installCRDs: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
