apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-ghcr-imagepullsecret
spec:
  background: false
  rules:
  - name: sync-imagepullsecret
    match:
      resources:
        kinds:
        - Namespace
    generate:
      kind: Secret
      name: ghcr
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        namespace: default
        name: ghcr
  validationFailureAction: audit
