apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator-ui
  namespace: argocd
spec:
  destination:
    namespace: pgo
    server: https://kubernetes.default.svc
  project: {{ .Values.argocd.project }}
  source:
    chart: postgres-operator-ui
    repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui/
    targetRevision: 1.8.2
    helm:
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
