apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
      - key: "/foo/bar"
        value: "HELLO1"
        version: "v1"
      - key: "/foo/bar"
        value: "HELLO2"
        version: "v2"
      - key: "/foo/baz"
        valueMap:
          foo: example
          other: thing
      # These look like real secrets below, but they are just for a local demo
      # use a real secret store in prod - like Vault, or AWS Secret Manager, etc.
      - key: "/web3auth"
        valueMap:
          clientId: web3auth-client
          clientSecret: a114d68b22894049a7c2203a7228fdcde922a1210675427795b7bf9a0317e16d
      - key: "/example-hasura"
        valueMap:
          adminSecret: af18a72fc1eb42a78aa8c6d679b4842a
          jwtSecret: '{"type":"HS256", "key": "a114d68b22894049a7c2203a7228fdcde922a1210675427795b7bf9a0317e16d"}'